### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by evgeniy-scherbina**
Implemented some rpc calls from TODOs

### CODE REVIEW

**Comment by evgeniy-scherbina** [comment]
It seems that CI fails through some problem with dependencies version. Can i fix it and send PR?

**Comment by thomaseizinger** [comment]
I fixed the build issue, sorry about that.

Which one of the two PRs (#19, #20) is the current one now? They both seem to contain the same changes.

**Comment by evgeniy-scherbina** [comment]
> I fixed the build issue, sorry about that.
> 
> Which one of the two PRs (#19, #20) is the current one now? They both seem to contain the same changes.

#19

**Comment by thomaseizinger** [comment]
Would you mind closing the other one then? Thanks!

**Comment by evgeniy-scherbina** [comment]
> Would you mind closing the other one then? Thanks!

Yeah, I've closed #20.

**Comment by evgeniy-scherbina** [comment]
Is there any block to merge this PR?

**Comment by thomaseizinger** [comment]
Unfortunately yes - the test you added is failing :)
Also, as mentioned above, I wasn't sure which of the two PRs you actually intended to contribute so I gave my feedback on the other one because it was more recent.
Do you plan on integrating that feedback? I added some thoughts on why the tests might be failing and suggested a way to solve it.

The branch will need a rebase against current master before it can be merged but that can happen as the last step. Note that I already integrated the formatting changes that occurred due to the latest Rust stable release. Means you can drop your formatting commit when rebasing against the current master.

**Comment by evgeniy-scherbina** [comment]
In #19 PR I was added two rpc calls `getblockhash`, `getbestblockhash` and tests for it. It seems working fine(all tests passed, OK with CI). 
In #20 i plan to implement more complex call `getblockverbose` and I've faced with some problem which I've mentioned. 

I think you can merge this PR and afterthat I'll finish implementation of `getblockverbose` RPC call in other PR and take into account your feedback.

I think I've confused you because #20 contains some changes from #19.

**Comment by thomaseizinger** [comment]
Ah okay, now I understand. Sorry about that, I thought it was the same PR!

About the test: You are right, seemed like a small hickup with the docker container. I re-triggered it and it worked now.

I'll rebase the PR against current master and then merge it!

**Pull request merged**
